### PR TITLE
Don't enforce 1 week limit on presigned urls.

### PR DESCRIPTION
**Pull request by dziemid**
We have run into this restriction while updating from v1 version of the gem.

### CODE REVIEW

**Comment by trevorrowe** [comment]
I'm afraid this is not technically possible. Removing the 1-week limit expiration will only permit the SDK to return invalid pre-signed URLs. Signatures extending beyond one week will not be honored by Amazon S3. This is a limitation of signature version 4 pre-signed URLs.

Version 2 of the SDK intentionally moved from v2 signatures to v4 signatures for security reasons. Additionally, v2 signatures simply do not work in an increasing number of scenarios, such as new Amazon S3 regions, operations involving encrypted objects and more.

**Comment by dziemid** [comment]
Thank you for quick answer.

Is 1-week limitation enforced across all the regions? We are currently using 60 days in us-east-1.

**Comment by trevorrowe** [comment]
I assume with the 60 days you are using the classic signature which does not have a limit on the expiration.

**Comment by dziemid** [comment]
Thank you, make sense.

In that case, happy to close this one.

**Pull request closed without merging**
