### PR TITLE
Allow setting config/credential files via environment variables

### PR DESCRIPTION
**Pull request by malept**
Adds support for setting the paths to the config and credentials files via environment variables, named the same as the ones used by botocore/awscli.
- config file: `AWS_CONFIG_FILE`
- credentials file: `AWS_SHARED_CREDENTIALS_FILE`

### CODE REVIEW

**Comment by awood45** [comment]
Considering if this would be a breaking change, but looks good at a first pass.

**Comment by awood45** [comment]
I've resolved to include this for `aws-sdk-core` 3.0, as there are already some semi-breaking changes involved there. Now considering merging it in sooner as the surface area for issues seems to be low.

**Comment by malept** [comment]
Out of curiosity, now that v3 is out, is this now bumped to v4, or could it go in sooner?

**Comment by awood45** [comment]
We will review this against V3. The upgrade from 2 to 3 promises no code breaking changes, that still holds, so adding this is fine.

**Comment by awood45** [comment]
We will need to open this PR again against V3 code, however, since the structure is a bit different.

**Comment by malept** [comment]
That's fine. I should be able to do that within the next week.

**Comment by malept** [comment]
I've rebased this PR on master.

**Comment by haines** [comment]
@awood45 sorry to be "that guy" but is there any chance of getting this in soon? It seems to be supported by the majority of the other SDKs, and we are relying on this feature (I've had to monkey-patch it in until this PR lands), so would really appreciate having it in the released gem.

Thanks ❤️

**Pull request merged**
