### PR TITLE
Fix JRuby Issues with IO.copy_stream

### PR DESCRIPTION
**Pull request by awood45**
In short, JRuby had some major issues around IO.copy_stream until about
`9.1.15.0`, with even more fixes coming in `9.1.16.0`. This proposed
patch works around that issue and integration tests are passing in
JRuby.

Fixes #1711

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

1. To make sure we include your contribution in the release notes, please make sure to add description entry for your changes in the "unreleased changes" section of the `CHANGELOG.md` file (at corresponding gem). For the description entry, please make sure it lives in one line and starts with `Feature` or `Issue` in the correct format.

2. For generated code changes, please checkout below instructions first:
  https://github.com/aws/aws-sdk-ruby/blob/master/CONTRIBUTING.md

Thank you for your contribution!

### CODE REVIEW

**Comment by awood45** [comment]
From the related issue #1711 - this issue is likely to increase memory usage by a decent amount, including outside of JRuby.

**Comment by Fonsan** [comment]
There is a memory usage increase. It will use twice the memory for when the stream is in memory mode and it will act as if in memory mode for tempfile which defeats the purpose of the tempfile apporach

**Comment by Fonsan** [comment]
There might be a convoluted way to make it backwards compatible by reading and writing small chunks but I think going down that road would prove some of the points I layed out in #1711

**Comment by Fonsan** [comment]
@awood45 Would you consider adding a explicit exception that would be raised if this functionality was called from a incompatible version of jruby allowing for a better experience for the developer?

**Comment by awood45** [comment]
That's definitely possible. There's a few ways to go about this that I'm comparing right now. Most ugly might be to have this approach as a fallback, or gating on language versions (the approach I most want to avoid).

I'm leaning towards the belief that punishing the vast majority of users with memory bloat just because JRuby's standard library was buggy is not the way to go. Question is how well we can support older JRuby versions.

**Comment by Fonsan** [comment]
I looked into reimplementing the same semantics as IO.copy_stream and realised that rubinius must do the same thing. 

https://github.com/rubinius/rubinius/blob/15b12dbf61f91f44851282af2956587eed9bc128/core/io.rb#L1041
https://github.com/rubinius/rubinius/blob/15b12dbf61f91f44851282af2956587eed9bc128/core/io.rb#L1123

But I am not even sure that they get it right as they call seek on the IO object and not all IO objects support seek

**Comment by Fonsan** [comment]
Nevermind the bit about seek, MRI makes the same assumption for the fourth parameter https://ruby-doc.org/core-2.3.1/IO.html#method-c-copy_stream

**Comment by awood45** [comment]
Ok, verdict - I'm going to go with your implementation with a documentation note about the JRuby issues. If we get reports about it, my fallback plan (which I'd rather not do) is to fork the logic to the memory bloat approach if and only if the user is using an old version of JRuby by checking the Ruby version at runtime.

**Pull request merged**
