### PR TITLE
Create .rspec and fix warnings.

### PR DESCRIPTION
**Pull request by ioquatix**
Warnings are an important part of Ruby's upgrade path. They indicate potential bugs or other issues with the code (for example, typos in `@instance_variable` names, clobbering functions, changes in default behaviour, etc) I suggest that this is enabled and that the code is fixed so that it no longer produces warnings.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ioquatix** [comment]
By the way, due to some of the warnings generated, some specs actually fail. That's a good indication that some areas of the code require more scrutiny.

**Comment by ioquatix** [comment]
See also https://github.com/aws/aws-sdk-ruby/issues/1778

**Comment by ioquatix** [comment]
The warnings from mustache should be fixable, there is an open issue here: https://github.com/mustache/mustache/issues/224

**Comment by ioquatix** [comment]
Bump :)

**Comment by ioquatix** [comment]
Bump :)

**Comment by ioquatix** [comment]
Hello, do you think you can either merge this PR or tell me why it can't be merged? Thanks.

**Comment by awood45** [comment]
Sorry for the delay here - let me work on a conflict resolution on the PR and this should be good to merge.

**Comment by diachini** [comment]
It looks like at least a part of this was maybe undone here:

https://github.com/aws/aws-sdk-ruby/commit/f4b3251658ee1d95403d7a851ace8495ea4115af#diff-eba7bf5f9cb1f1ef94f03eeba1444966L24 

and here: https://github.com/aws/aws-sdk-ruby/commit/aca0d7cb31d1715b60711cbb907623fab498b595

(I was updating the aws-sdk-s3 gem in one of my teams' projects, and was just hoping to get an understanding of why this was added and then removed?)

**Comment by awood45** [comment]
This broke our automated release process. I'm looking in to why that is
before re-adding the warnings file.

**Comment by ioquatix** [comment]
@awood45 did you ever revisit this?

**Comment by cjyclaire** [comment]
apologies for the delay, mind opening an new issue/PR so I can track this?

**Pull request merged**
