### PR TITLE
fixed bugs [CloudFront/RDS] and added new waiters [OpsWorks/ElastiCache/CloudFormation/EC2]

### PR DESCRIPTION
**Pull request by eniskonuk**
Fixed a couple of problems in the CloudFront and RDS waiters
Added new waiters for OpsWorks, ElastiCache, Cloudformation and EC2

### CODE REVIEW

**Comment by trevorrowe** [comment]
Just a heads up. I hope to check this out later today. Theres quite a bit to review. Thank you for the contributions!

**Comment by eniskonuk** [comment]
Thanks for the note. Take your time. We're using our forked version of the gem at the moment and will switch over once everything is merged and released. There are probably some additional waiters that we'll add later.

**Comment by eniskonuk** [comment]
@trevorrowe: Any update on this?

**Comment by trevorrowe** [comment]
Thank you for the contributions!

**Comment by eniskonuk** [comment]
Awesome. Thanks for the merge. More to come in the future.

**Pull request merged**
