### PR TITLE
aws-sdk-dynamodb - Allow objects responding to #to_h to be marshaled as a Hash

### PR DESCRIPTION
**Pull request by alexagranov**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

1. To make sure we include your contribution in the release notes, please make sure to add description entry for your changes in the "unreleased changes" section of the `CHANGELOG.md` file (at corresponding gem). For the description entry, please make sure it lives in one line and starts with `Feature` or `Issue` in the correct format.

2. For generated code changes, please checkout below instructions first:
  https://github.com/aws/aws-sdk-ruby/blob/master/CONTRIBUTING.md

Thank you for your contribution!

### CODE REVIEW

**Comment by alexagranov** [comment]
If accepted, I can make a similar PR against `version2` branch.

**Comment by alexagranov** [comment]
Updated spec to pass on 1.9.3 (was using OpenStruct but no `to_h` for 1.9.3 :-()

**Comment by awood45** [comment]
This is kind of an interesting case, it sounds like we're expecting different behavior in 1.9.3 if adopting this change?

**Comment by awood45** [comment]
Ahh, I'm understanding the purpose a bit more. I am concerned though that this could catch some objects which weren't intended to be treated as hashes. Granted, we survive this now because of ordering, but I'm now considering if it's important to explicitly ask you to USE your hash transformation ability before calling low-level clients.

**Comment by alexagranov** [comment]
Hi, thanks for getting back to this.

I do see the merit in requiring clients of an SDK to explicitly provide proper objects to marshal - otherwise raise an exception.  

But then couldn't one make the similar argument for not automatically calling `to_s` on provided objects?

I think `to_h` on Ruby objects has reached sufficient ubiquity that automatically marshaling with it if found could be reasonable.  Up to you of course but made sense to me to offer.

**Comment by awood45** [comment]
Your counterpoint is fair as well, though we'd have big problems if we implemented, for example, the `:to_s` check in the same way. Different because this is at the end of the switch stack, but just something I need to think about.

Not worried about the 1.9.3 point anymore, I was confusing myself on the OpenStruct emphasis. No worries, you're correct on that count.

**Comment by alexagranov** [comment]
Sounds good, let me know what you decide.  Happy to tackle specs from a different perspective/direction if you have something in mind.

**Comment by mullermp** [comment]
@alexagranov Sorry that this issue was dropped. We took a look and think it should be safe to merge.

**Pull request merged**
