### PR TITLE
Add waiter for SecurityGroup exists

### PR DESCRIPTION
**Pull request by smcavallo**
Add waiter for SecurityGroup exists.  The `wait_until` method on the SecurityGroup class has been deprecated and does not have a corresponding replacement per `# @deprecated Use [Aws::EC2::Client] #wait_until instead`

Signed-off-by: S.Cavallo <smcavallo@hotmail.com>

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

1. To make sure we include your contribution in the release notes, please make sure to add description entry for your changes in the "unreleased changes" section of the `CHANGELOG.md` file (at corresponding gem). For the description entry, please make sure it lives in one line and starts with `Feature` or `Issue` in the correct format.

2. For generated code changes, please checkout below instructions first:
  https://github.com/aws/aws-sdk-ruby/blob/master/CONTRIBUTING.md

Thank you for your contribution!

### CODE REVIEW

**Comment by smcavallo** [comment]
@cjyclaire - hoping you can provide any feedback here

**Comment by mullermp** [comment]
Hello. Thank you for the contribution. Apologies for the delay here. These changes are made to auto generated files, so I cannot merge these as is. I would have to apply these upstream in conjunction with the ec2 team. Have you tested these changes by chance and/or have any code snippets?

**Comment by mullermp** [comment]
Hey there - sorry for the late response. We can't take this PR because it is against auto generated code. I will try to add this code upstream but first I must test it.

**Comment by mullermp** [comment]
I've tested this change and merged it upstream. In the coming weeks I will get this feature shipped to the SDKs.

**Comment by smcavallo** [comment]
@mullermp - any update on this?  I still don't see it in the master branch

**Comment by mullermp** [comment]
https://github.com/aws/aws-sdk-ruby/blob/master/apis/ec2/2016-11-15/waiters-2.json#L382-L399

It should be here!

**Pull request closed without merging**
