### PR TITLE
Add enhanced presign request feature

### PR DESCRIPTION
**Pull request by cjyclaire**
This PR adds support for `Aws::S3::PresignedRequest` that allows more flexible and customized presigned behaviors, refractored based on `aws-sigv4` gem and provides helpful `#headers` for bucket policy work arounds etc..

Documentations and tests(rspec & smoke) both have been addressed in the PR, here is a sample usage:
``` ruby
req = Aws::S3::PresignedRequest.new(:put_object,
  bucket: 'bktname',
  key: 'key',
  acl: 'private',
  cache_control: 'max-age=20000'
  headers: {
    'foo' => 'bar',
    'cache_control' => 'max-age=20000'
  }
)

req.uri
# => #<URI::HTTPS https://bktname. ... .&X-Amz-SignedHeaders=host%3Bx-amz-acl%3Bx-amz-canche-control%3Bx-amz-foo...

req.headers
# => {"x-amz-acl"=>"private", "x-amz-canche-control" => "max-age=20000", "x-amz-foo"=>"bar"}
```

Related issues, PRs and feature requests:
https://github.com/aws/aws-sdk-ruby/issues/874, https://github.com/aws/aws-sdk-ruby/issues/1152, https://github.com/aws/aws-sdk-ruby/issues/1384
https://github.com/aws/aws-sdk-ruby/pull/1228, https://github.com/aws/aws-sdk-ruby/pull/1403 ( https://github.com/aws/aws-sdk-ruby/issues/1400, https://github.com/aws/aws-sdk-ruby/issues/1401)
#2098 

cc:\ @awood45 @trevorrowe

### CODE REVIEW

**Comment by cjyclaire** [comment]
Still in progress, yet have finished refractor using client request handler in constructing urls.

**Comment by cjyclaire** [comment]
Based on the discussion our team had off-line, we will work on a more generalized solution that brings much more benefits and flexibility in the long run. And that is a feature has been prioritized which will be shipped through Modularization Ruby SDK which is currently under preview release and will be in GA in the near future.

Meanwhile, [`aws-sigv4`](https://rubygems.org/gems/aws-sigv4) gem is available for general, flexible and customized presign behavior and signer usage, with [fully documented source code](https://github.com/aws/aws-sdk-ruby/tree/code-generation/gems/aws-sigv4)

This PR will still be kept opened for a while for feedbacks and thoughts! : )

**Comment by oyeanuj** [comment]
@cjyclaire I am using v3 and the code below, but wondering how can I add a custom header to my PUT request. Adding it on the client-side throws an error, so it seems like I must do it while creating the pre-signed url?

```rb
signer = Aws::S3::Presigner.new(client: s3)
self.presigned_url = signer.presigned_url(
  :put_object,
  bucket:	self.bucket,
  key:	self.file_key
)
```

So, is it possible right now in v3? If not, what would be the equivalent code for the code above with the gem mentioned above?

Thank you!

**Comment by cjyclaire** [comment]
@oyeanuj Sure, you can do it both in V2 and V3, yet I'd recommend using the `aws-sigv4` gem with code snippets as below:
``` ruby
require `aws-sigv4`

# a s3 client at region 'us-west-2'
signer = Aws::Sigv4::Signer.new( 
  service: 's3', 
  region: 'us-west-2', 
  credentials_provider: client.config.credentials, 
  uri_escape_path: false, 
)

# create presigned url for an object with bucket 'a-fancy-bucket' and key 'hello_world' 
url = signer.presign_url( 
  http_method: 'PUT', 
  url:'https://a-fancy-bucket.s3-us-west-2.amazonaws.com/hello_world', 
  headers: {                                                                                                                             
     "x-amz-foo" => "bar"                                                                                       
  } 
  body_digest: 'UNSIGNED-PAYLOAD', 
) 

# making request
body = ...
Net::HTTP.start(url.host) do |http|
  http.send_request("PUT", url.request_uri, body, { 
    "x-amz-foo" => "bar", 
  })
end
# => #<Net::HTTPOK 200 OK readbody=true>
```

**Comment by oyeanuj** [comment]
@cjyclaire Thanks! Just curious, is there an advantage of using `aws-sigv4` over v3 `aws-sdk-s3`? FWIW, I need the url just to pass to the client side to make the request.

**Comment by mullermp** [comment]
Closing - I think this solution solves this case? https://github.com/aws/aws-sdk-ruby/issues/874#issuecomment-634968105

**Pull request closed without merging**
