### PR TITLE
Fix to support URI encoded characters in http_proxy

### PR DESCRIPTION
**Pull request by Fryguy**
See #458, where this was fixed previously but was somehow lost.

As this class has no specs previously, I broke the part I changed out into a separate private method and just tested that.  I was unsure how to test it end-to-end, otherwise.

### CODE REVIEW

**Comment by Fryguy** [comment]
@trevorrowe Please review?

**Comment by Fryguy** [comment]
Gah...I missed this comment...I'll add it right away.

**Comment by Fryguy** [comment]
@cjyclaire Oh, it seems I've already done that... https://github.com/aws/aws-sdk-ruby/pull/1760/files#diff-4fe8ce5547b24bcbfe5ebd2206060363R5

**Comment by Fryguy** [comment]
@trevorrowe @cjyclaire bump?

**Comment by cjyclaire** [comment]
@Fryguy Could you pull/rebase latest changes into this PR? 😃
We need to use the [unreleased changes section](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/CHANGELOG.md) to do correct version bummp

**Comment by Fryguy** [comment]
@cjyclaire Done!

**Comment by cjyclaire** [comment]
Thanks! I'll merge it once CI complete, it should be included in the next release

**Pull request merged**
