### PR TITLE
Fixed the invocation of refresh! method on SharedCredentials

### LINKED ISSUE #2685: refresh! method is being called on Aws::SharedCredentials
### Describe the bug

The `Aws::SharedCredentials` class doesn't have the `refresh!` method implemented since this is not a refreshable credential class. Whenever we use this class for storing credentials and the credentials are expired, the SDK will try to call the `refresh!` method and will raise the following error. 

```ruby
NoMethodError (undefined method `refresh!' for #<Aws::SharedCredentials profile_name="default" path="/home/ubuntu/.aws/credentials">)
```

### Expected Behavior

The user should not be seeing these error messages. If the credentials are expired, show a corresponding error message.

### Current Behavior

Currently, this is throwing the NoMethodError.

### Reproduction Steps

For reproducing the error skew the clock first.
```shell
~$ sudo timedatectl set-ntp no
~$ sudo timedatectl set-time 12:17:13 # skewed past 15 minutes
~$ aws sts get-caller-identity
An error occurred (SignatureDoesNotMatch) when calling the GetCallerIdentity operation: Signature not yet current: 20220412T132639Z is still later than 20220412T124047Z (20220412T122547Z + 15 min.)
```

Now open the ruby console and initialize the client and call the describe_images method:
```ruby
3.0.0 :005 > ::Aws.config.update(region: 'us-east-2', profile: 'default', http_proxy: nil, ssl_verify_peer: true)
 => {:region=>"us-east-2", :profile=>"default", :http_proxy=>nil, :ssl_verify_peer=>true}

3.0.0 :006 > client = Aws::EC2::Client.new
 => #<Aws::EC2::Client>

3.0.0 :007 > client.describe_images({:image_ids=>["ami-0fb653ca2d3203ac1"]})
Traceback (most recent call last):
       16: from /usr/share/rvm/gems/ruby-3.0.0/gems/aws-sdk-core-3.130.0/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
       15: from /usr/share/rvm/gems/ruby-3.0.0/gems/aws-sdk-core-3.130.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:22:in `call'
       14: from /usr/share/rvm/gems/ruby-3.0.0/gems/aws-sdk-core-3.130.0/lib/aws-sdk-core/plugins/checksum_algorithm.rb:111:in `call'
       13: from /usr/share/rvm/gems/ruby-3.0.0/gems/aws-sdk-core-3.130.0/lib/seahorse/client/plugins/raise_response_errors.rb:16:in `call'
       12: from /usr/share/rvm/gems/ruby-3.0.0/gems/aws-sdk-core-3.130.0/lib/aws-sdk-core/plugins/param_validator.rb:26:in `call'
       11: from /usr/share/rvm/gems/ruby-3.0.0/gems/aws-sdk-core-3.130.0/lib/seahorse/client/plugins/endpoint.rb:47:in `call'
       10: from /usr/share/rvm/gems/ruby-3.0.0/gems/aws-sdk-core-3.130.0/lib/aws-sdk-core/plugins/endpoint_discovery.rb:80:in `call'
        9: from /usr/share/rvm/gems/ruby-3.0.0/gems/aws-sdk-core-3.130.0/lib/aws-sdk-core/plugins/user_agent.rb:13:in `call'
        8: from /usr/share/rvm/gems/ruby-3.0.0/gems/aws-sdk-core-3.130.0/lib/aws-sdk-core/plugins/recursion_detection.rb:18:in `call'
        7: from /usr/share/rvm/gems/ruby-3.0.0/gems/aws-sdk-core-3.130.0/lib/aws-sdk-core/query/handler.rb:30:in `call'
        6: from /usr/share/rvm/gems/ruby-3.0.0/gems/aws-sdk-core-3.130.0/lib/aws-sdk-core/plugins/checksum_algorithm.rb:136:in `call'
        5: from /usr/share/rvm/gems/ruby-3.0.0/gems/aws-sdk-core-3.130.0/lib/aws-sdk-core/plugins/endpoint_pattern.rb:30:in `call'
        4: from /usr/share/rvm/gems/ruby-3.0.0/gems/aws-sdk-core-3.130.0/lib/aws-sdk-core/plugins/http_checksum.rb:19:in `call'
        3: from /usr/share/rvm/gems/ruby-3.0.0/gems/aws-sdk-core-3.130.0/lib/aws-sdk-core/plugins/retry_errors.rb:368:in `call'
        2: from /usr/share/rvm/gems/ruby-3.0.0/gems/aws-sdk-core-3.130.0/lib/aws-sdk-core/plugins/retry_errors.rb:381:in `retry_if_possible'
        1: from /usr/share/rvm/gems/ruby-3.0.0/gems/aws-sdk-core-3.130.0/lib/aws-sdk-core/plugins/retry_errors.rb:392:in `retry_request'
NoMethodError (undefined method `refresh!' for #<Aws::SharedCredentials profile_name="default" path="/home/ubuntu/.aws/credentials">)
```

### Possible Solution

Since the `refresh!` method is not available for the Aws::SharedCredentials, add that condition as well before trying to refresh the credentials. 

### Additional Information/Context

https://github.com/test-kitchen/kitchen-ec2/issues/576

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-core-3.130.0

### Environment details (Version of Ruby, OS environment)

ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]

### PR DESCRIPTION
**Pull request by ashiqueps**
Signed-off-by: Ashique Saidalavi <ashique.saidalavi@progress.com>

Fixes: #2685 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

1. To make sure we include your contribution in the release notes, please make sure to add description entry for your changes in the "unreleased changes" section of the `CHANGELOG.md` file (at corresponding gem). For the description entry, please make sure it lives in one line and starts with `Feature` or `Issue` in the correct format.

2. For generated code changes, please checkout below instructions first:
  https://github.com/aws/aws-sdk-ruby/blob/version-3/CONTRIBUTING.md

Thank you for your contribution!

### CODE REVIEW

**Comment by alextwoods** [comment]
Thanks for opening this - looks like a good fix - I'm reviewing.

**Comment by alextwoods** [comment]
I'm still trying to dig into this a bit more - but the [ErrorInspector#retryable?](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-core/lib/aws-sdk-core/plugins/retries/error_inspector.rb#L126) method should already be checking for this and if credentials are not refreshable (does not respond to `:refresh!`) then the error will not be considered retryable and we shouldn't get to this code.

**Comment by ashiqueps** [comment]
@alextwoods 

Oh I see, I actually missed that class. For me the `clock_skew?` method was returning true always resulting true for `retryable?` method as well.

**Comment by alextwoods** [comment]
Yeah - you're correct!  Its possible for some errors to be considered both retryable and expired_credentials.  So I do believe the approach in this PR is correct - we need to check in both places.

**Comment by alextwoods** [comment]
I've pushed a small update - there are two error handlers (legacy/standard) and I've applied the check to both.  Also added some specs.

**Review by alextwoods — APPROVED** [review]

**Comment by alextwoods** [comment]
I've gone ahead and merged this - it should be released tomorrow.  Thanks again for the contribution!

**Comment by ashiqueps** [comment]
Thanks a lot for all the help @alextwoods. It is much appreciated.

**Pull request merged**
