### PR TITLE
Support unsigned_request for cognito-identity

### PR DESCRIPTION
**Pull request by DianthuDia**

### CODE REVIEW

**Comment by trevorrowe** [comment]
I'm not very familiar with the Cognito Identity API, but I looked at the API reference documentation for a few of these operations and their documented examples use an authorization header. Are these strictly unsigned operations, or could/should they be conditionally signed?

**Comment by DianthuDia** [comment]
Yes, documented examples use an authorization header. But please check beginning of the description.

http://docs.aws.amazon.com/cognitoidentity/latest/APIReference/API_GetId.html

> This is a public API. You do not need any credentials to call this API.

**Comment by trevorrowe** [comment]
This should go out with the next release shortly.

**Comment by DianthuDia** [comment]
Thank you for merging and adding test :yellow_heart:

**Pull request merged**
