### PR TITLE
Add the last missing frozen_string_literals comments

### PR DESCRIPTION
**Pull request by casperisfine**
Followup: #2328

Since there isn't any big gem left, but many groups of a few files in many different gems, I opted for submitted all the last changes as a single PR.

I simply ran:

```bash
rubocop -a --only Style/FrozenStringLiteralComment,Layout/EmptyLineAfterMagicComment
```

I also adjusted the line numbers in `region_spec.rb`.

### CODE REVIEW

**Comment by mullermp** [comment]
Uh oh, checking the build output, in both ec2 and s3 clients, this is shown in the docs:

```
     # @example Streaming a file from disk
+    #   # frozen_string_literal: true
+    #
```

Hopefully this wasn't merged in the previous CRs?

**Comment by casperisfine** [comment]
Hopefully not, but that's the issue I witnessed in the original PR. If you have a few pointers as to where these snippets are extracted I could take a look at updating the code so that it ignores the `# frozen_string_literal: true`.

**Comment by mullermp** [comment]
Ah! I think because the examples in `doc-src/examples/` are loaded as comments. You may want to exclude changes to those files.

**Comment by mullermp** [comment]
Only s3 and ec2 have examples there, which makes sense.

**Comment by casperisfine** [comment]
Makes total sense.I just removed it.

**Comment by mullermp** [comment]
Thanks for the contribution!

**Pull request merged**
