### PR TITLE
Added Aws::CloudFormation::Stack#create

### PR DESCRIPTION
**Pull request by stopdropandrew**
Meant to submit this back when I did https://github.com/aws/aws-sdk-ruby/pull/975 but I forgot. I've rebased onto master and it should be ready to go.

### CODE REVIEW

**Comment by awood45** [comment]
Looks good, but will need to rebase one more time due to the CHANGELOG updating.

**Comment by stopdropandrew** [comment]
@awood45 rebased, thanks!

**Comment by stopdropandrew** [comment]
@awood45 bump, would love to get this merged

**Comment by awood45** [comment]
Sorry, this looks good and I'll merge/push up the change.

**Pull request merged**
