### PR TITLE
Ensure locking around `@entries`. Fixes #2142.

### LINKED ISSUE #2142: thread safety issues in endpoint_cache.rb
```ruby
    # @param [String] key
    # @param [Hash] value
    def []=(key, value)
      @mutex.synchronize do
        # delete the least recent used endpoint when cache is full
        unless @entries.size < @max_entries
          old_key, _ = @entries.shift
          self.delete_polling_thread(old_key)
        end
        # delete old value if exists
        @entries.delete(key)
        @entries[key] = Endpoint.new(value.to_hash)
      end
    end

    # checking whether an unexpired endpoint key exists in cache
    # @param [String] key
    # @return [Boolean]
    def key?(key)
      if @entries.key?(key) && (@entries[key].nil? || @entries[key].expired?)
        self.delete(key)
      end
      @entries.key?(key)
    end
```

This does not look thread safe to me. If multiple threads are accessing @entries, `#key?` can be called without locking around `@entries`. I don't believe those are thread-safe operations.

### PR DESCRIPTION
**Pull request by ioquatix**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

1. To make sure we include your contribution in the release notes, please make sure to add description entry for your changes in the "unreleased changes" section of the `CHANGELOG.md` file (at corresponding gem). For the description entry, please make sure it lives in one line and starts with `Feature` or `Issue` in the correct format.

2. For generated code changes, please checkout below instructions first:
  https://github.com/aws/aws-sdk-ruby/blob/master/CONTRIBUTING.md

Thank you for your contribution!

### CODE REVIEW

**Comment by mullermp** [comment]
Thanks for the contribution!

**Comment by ioquatix** [comment]
I am happy to provide feedback on other thread related issues but perhaps AWS can consider sponsoring my open source work so I can dedicate more time to it. Let me know if this is something worth exploring.

**Comment by mullermp** [comment]
I may take you up on that if we ever run into any thread safe issues, and thanks for bringing this to our attention.

Regarding sponsorships, I've never looked into it, I'll ask around internally.

**Comment by ioquatix** [comment]
During my review I found other potentially unsafe code. Sponsorship or consulting are two options available if you want more of my time. Thanks for investigating it internally.

**Pull request merged**
