### PR TITLE
Mention MIGRATING.md in UPGRADING.md

### PR DESCRIPTION
**Pull request by jaredbeck**
[ci skip]

### CODE REVIEW

**Comment by cjyclaire** [comment]
@jaredbeck Appreciate your thoughts on this PR! Yet `UPGRADING.md` is the file used to tracking release note automatically for V2. Instead of having the note here, we already mentioned `MIGRATING.md` in main [`README.md`](https://github.com/aws/aws-sdk-ruby/blob/master/README.md#nameerror-uninitialized-constant-aws). Thank you all the same!

**Comment by jaredbeck** [comment]
> @jaredbeck Appreciate your thoughts on this PR! Yet UPGRADING.md is the file used to tracking release note automatically for V2. Instead of having the note here, we already mentioned MIGRATING.md in main README.md. Thank you all the same!

When I wanted to upgrade from 1 to 2, I looked in the file named "upgrading". Seems like a mistake to choose not to help people who think the same way.

**Comment by cjyclaire** [comment]
@jaredbeck Apology for this, taking a second look, it's `CHANGELOG.md` is automated actually.
I'll merged this PR instead. Appreciate your patience on this!

**Comment by jaredbeck** [comment]
> @jaredbeck Apology for this, taking a second look, it's CHANGELOG.md is automated actually.
I'll merged this PR instead. Appreciate your patience on this!

Cool, thanks for taking a second look. :)

**Pull request merged**
