### PR TITLE
Add Aws::Shield pagination for ListAttacks and ListProtections API calls

### PR DESCRIPTION
**Pull request by phene**
Add missing paginator definitions for Shield API calls

### CODE REVIEW

**Comment by mullermp** [comment]
Thank you for your contribution. Waiters come from an internal upstream source, so I cannot merge these as is. I can take these changes and apply them upstream so that all SDKs have them.

**Comment by phene** [comment]
This PR is for pagination, @mullermp

**Comment by mullermp** [comment]
@phene Ah sorry, I saw the previous PR and carried it forward. The same case applies to both paginators, waiters, and resources.

**Comment by phene** [comment]
I'd reiterate my [comment from the other PR](https://github.com/aws/aws-sdk-ruby/pull/2245#issuecomment-594701909)

**Comment by mullermp** [comment]
I've posted this change in a code review upstream. After it is merged, it will be included in Shield's next release.

**Comment by mullermp** [comment]
Soft update - Shield is doing an API update next month and I have made sure that these paginators will be included.

**Comment by mullermp** [comment]
These have been added 10 days ago: https://github.com/aws/aws-sdk-ruby/blob/master/apis/shield/2016-06-02/paginators-1.json

**Comment by mullermp** [comment]
Thanks for the contribution!

**Pull request closed without merging**
