### PR TITLE
Added Kinesis Exception to ErrorInspector

### PR DESCRIPTION
**Pull request by wltbenade**
Submitting this as per https://github.com/awslabs/aws-fluent-plugin-kinesis/issues/217#issuecomment-1003256969 in order to resolve credential rotation issues in github.com/awslabs/aws-fluent-plugin-kinesis.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

1. To make sure we include your contribution in the release notes, please make sure to add description entry for your changes in the "unreleased changes" section of the `CHANGELOG.md` file (at corresponding gem). For the description entry, please make sure it lives in one line and starts with `Feature` or `Issue` in the correct format.

2. For generated code changes, please checkout below instructions first:
  https://github.com/aws/aws-sdk-ruby/blob/version-3/CONTRIBUTING.md

Thank you for your contribution!

### CODE REVIEW

**Comment by mullermp** [comment]
Can you update tests? https://github.com/aws/aws-sdk-ruby/blob/45a276da5ebdc3678fcdb25634bd57b0b0daf215/gems/aws-sdk-core/spec/aws/plugins/retries/error_inspector_spec.rb#L15

**Comment by wltbenade** [comment]
Hi @mullermp,

I have updated the tests as requested as well. 

Thanks!

**Comment by mullermp** [comment]
Thanks for your contribution!

**Comment by mullermp** [comment]
https://github.com/aws/aws-sdk-ruby/commit/c3837bfe43449a833f12b656d9ce10f3ed18279e

Added changelog, it should release today.

**Comment by wltbenade** [comment]
Hi @mullermp,

Is there any word on when the next release will be made available?

**Comment by mullermp** [comment]
This was already released as core version 3.125.3

**Comment by wltbenade** [comment]
MY apologies @mullermp! I was keeping an eye on the releases page.

Thanks for everything!

**Pull request merged**
