### PR TITLE
Fixes `to_json` usage on pageable responses in custom objects

### LINKED ISSUE #2732: `to_json` causing `SystemStackError` for SES response in v3
### Describe the bug

`send_raw_email` method on `Aws::SES::Client` object returns a `Aws::SES::Types::SendRawEmailResponse` which should be supporting `to_json` but on **v3** it is causing `SystemStackError: stack level too deep`. 
It was working fine in **v2**.

### Expected Behavior

It should return a valid JSON string.

### Current Behavior

Currently it is causing `SystemStackError: stack level too deep`,

### Reproduction Steps

call `send_raw_email` method on a valid `Aws::SES::Client` object and call `to_json` method for the response.

### Possible Solution

I tried calling the `to_s` method for both v2 & v3 versions.

On V2, `to_s` returns `"#<struct Aws::SES::Types::SendRawEmailResponse message_id=\"01010182363d52db-5bcb1ffd-f7aa-4863-b383-8f984cac1e6a-000000\">"`

On V3, `to_s` returns `"{:message_id=>\"0111118236469049-ec2d2a68-9eb1-411f-9f70-e50ae14de671-1110000\"}"`

This might help in fixing it.

### Additional Information/Context

I think this behavior has changed because of https://github.com/aws/aws-sdk-ruby/blame/e969f29e23f4930ff58728c5215a2e22fb2578cd/gems/aws-sdk-core/lib/aws-sdk-core/structure.rb#L51

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

'aws-sdk-ses'

### Environment details (Version of Ruby, OS environment)

Any version

### PR DESCRIPTION
**Pull request by rishabhsairawat**
This PR aims to resolve #2732. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

1. To make sure we include your contribution in the release notes, please make sure to add description entry for your changes in the "unreleased changes" section of the `CHANGELOG.md` file (at corresponding gem). For the description entry, please make sure it lives in one line and starts with `Feature` or `Issue` in the correct format.

2. For generated code changes, please checkout below instructions first:
  https://github.com/aws/aws-sdk-ruby/blob/version-3/CONTRIBUTING.md

Thank you for your contribution!

### CODE REVIEW

**Review by mullermp — APPROVED** [review]
Thanks for the bug fix! This seems fine.

**Comment by mullermp** [comment]
Actually.. I think we need to revert this. Does this work without rails usage?

**Comment by alextwoods** [comment]
Yeah, I think this will fail as is without rails, since the `as_json` method won't be defined on hash.

**Comment by rishabhsairawat** [comment]
Oops.. Sorry :tired_face:  
Yes, It won't work without rails. I should have put the check for that.

**Pull request merged**
