### PR TITLE
Run test with ruby 2.3.3

### PR DESCRIPTION
**Pull request by ojiry**
#### Purpose
Test with latest ruby version.

#### Changes
Modify ruby version of .travis.yml.

### CODE REVIEW

**Comment by awood45** [comment]
Any particular reason we want to change the version here? I'm more inclined to add Ruby 2.4 as it comes out rather than extend into additional point changes unless there's a particular change to concern ourselves with.

**Comment by ojiry** [comment]
> Any particular reason we want to change the version here?

Because we using the latest ruby, we want to verify by Travis CI.

>  I'm more inclined  to add Ruby 2.4~

I'm sorry. My English was poor and I couldn't understand the meaning of the second half. 🙇

**Comment by awood45** [comment]
I'm going to decline this PR, but I will make a change to try and remove the `2.3.0` point and test `2.3` instead. That should solve the problem you're mentioning and would be more consistent with how we test other Ruby versions. Thanks for bringing this to our attention!

**Comment by ojiry** [comment]
I agree with it. Thanks.

**Pull request closed without merging**
