### PR TITLE
Add documentation for conflicting members, add entries to UnsafeEnumerableMethods

### LINKED ISSUE #2534: [aws-sdk-personalize] `Types::DescribeFilterResponse#filter` unexpected return value
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers

**Describe the question**
Hi.
Is this intentional?
```ruby
client = Aws::Personalize::Client.new(region: 'ap-northeast-1')

describe_filter_response = client.describe_filter(filter_arn: 'masked value')
#=> #<struct Aws::Personalize::Types::DescribeFilterResponse
 filter=
  #<struct Aws::Personalize::Types::Filter
   name="exclude-effectived-filter",
   filter_arn="masked value",
   creation_date_time=2021-06-08 20:00:30 47317/131072 +0900,
   last_updated_date_time=2021-06-08 20:01:01 231211/262144 +0900,
   dataset_group_arn="masked value",
   failure_reason=nil,
   filter_expression="EXCLUDE ItemID WHERE Interactions.event_type IN (\"effectived\")",
   status="ACTIVE">>

describe_filter_response.filter
#=> #<Enumerator: ...>
```

```ruby
# I expected:

#=> #<struct Aws::Personalize::Types::Filter
 name="exclude-effectived-filter",
 filter_arn="masked value",
 creation_date_time=2021-06-08 20:32:35 2302673/4194304 +0900,
 last_updated_date_time=2021-06-08 20:33:11 1639973/2097152 +0900,
 dataset_group_arn="masked value",
 failure_reason=nil,
 filter_expression="EXCLUDE ItemID WHERE Interactions.event_type IN (\"effectived\")",
 status="ACTIVE">
```

**Version**
- Ruby: 2.7.2
- aws-sdk-personalize: 1.26.0

### PR DESCRIPTION
**Pull request by alextwoods**
Fixes #2534 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

1. To make sure we include your contribution in the release notes, please make sure to add description entry for your changes in the "unreleased changes" section of the `CHANGELOG.md` file (at corresponding gem). For the description entry, please make sure it lives in one line and starts with `Feature` or `Issue` in the correct format.

2. For generated code changes, please checkout below instructions first:
  https://github.com/aws/aws-sdk-ruby/blob/version-3/CONTRIBUTING.md

Thank you for your contribution!

### CODE REVIEW

**Review by mullermp — APPROVED** [review]
This seems fine to me. It's strange none of these were reported though. Are we sure that "entries" and "partition" actually cause issues?

**Comment by alextwoods** [comment]
`partition` causes the same issue as `filter`.  However, `entries` is trickier - it will return an array (similar to what the `data.entries` would, but of a different type) and for a paginated api, it will retrieve all of the pages, which could be unintended.

**Comment by mullermp** [comment]
If `entries` is returning all pages, should it be added as an unsafe method and raise?

**Comment by alextwoods** [comment]
I'd argue it *should* have been - but at this point that would be a breaking change for anyone thats relying on the behavior.

**Pull request merged**
