### PR TITLE
Taking AWS_REGION env as default region

### LINKED ISSUE #2112: Feature request: pre-populate Aws.config from environment
### Issue description

Would it be feasible to pre-populate `Aws.config` from the runtime environment?  For example, if `ENV["AWS_REGION"]` is set (and non-empty), then by default `Aws.config[:region] == ENV["AWS_REGION"]`.  Likewise for any settings picked up from "~/.aws" or elsewhere.

This would enable in-app configuration code like the following:
```ruby
Aws.config[:region] ||= "us-east-1"
```

Where a reasonable default is provided, but can overridden from the outside, without code modification.

Additionally, it may be useful when one wants to test what config values are being picked up from the environment, for example, when debugging.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

`aws-sdk`

### Version of Ruby, OS environment

any

### Code snippets / steps to reproduce

N/A

### PR DESCRIPTION
**Pull request by sivagollapalli**
FIX #2112 issue
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

1. To make sure we include your contribution in the release notes, please make sure to add description entry for your changes in the "unreleased changes" section of the `CHANGELOG.md` file (at corresponding gem). For the description entry, please make sure it lives in one line and starts with `Feature` or `Issue` in the correct format.

2. For generated code changes, please checkout below instructions first:
  https://github.com/aws/aws-sdk-ruby/blob/master/CONTRIBUTING.md

Thank you for your contribution!

### CODE REVIEW

**Comment by alextwoods** [comment]
The SDK will already look for region (and other config values) in the ENV before other sources (See this [dev guide](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/setup-config.html#aws-ruby-sdk-setting-credentials) for an overview of the order of preference or to see the code itself: [CredentialProviderChain](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/aws-sdk-core/credential_provider_chain.rb)).

**Comment by mullermp** [comment]
This doesn't fix the issue unfortunately. :( Thanks for opening the PR.

**Comment by sivagollapalli** [comment]
@mullermp No problem. I will try to fix.

**Comment by alextwoods** [comment]
@sivagollapalli - I don't think we should be changing the default behavior of Aws.config here (without a major version bump) as this could break current users.  Aws.config is easy to update in application code, so users are not blocked from doing this themselves if its behavior they want.

**Comment by sivagollapalli** [comment]
@alextwoods Would that mean are we discarding this issue #2112 or we are postponing till next major release?

**Pull request closed without merging**
