### PR TITLE
Add Aws::EC2::Vpc#exists?

### PR DESCRIPTION
**Pull request by kayvonghaffari**

### CODE REVIEW

**Comment by kayvonghaffari** [comment]
First time doing an Open Source Pull Request. Let me know if I'm doing this correctly!

Also, this feature has NOT been tested yet. What's the best way for me to test this in my development environment? Thanks!

**Comment by awood45** [comment]
Best way to test is to run it with your local client. In your development directory, can run `./aws-sdk-core/bin/aws.rb` to get an interactive shell with your changes. Then test on actual AWS resources.

I'm happy to do that for you with my account if you'd prefer, because this looks good at a glance. I'd revert the CHANGELOG change though, as that tends to cause merge conflicts. I'll happily add that for you (in fact, that will happen via our release scripts once I push this change up to the other SDKs).

**Comment by awood45** [comment]
Sorry about the delayed response here - fix the merge conflict issue and I'll get this tested and merged.

**Comment by trevorrowe** [comment]
This has been merged and will ship with our next release. I made a minor change to add a VpcExists waiter. `Aws::EC2::VPC` now has both exists and available waiters available.

**Comment by trevorrowe** [comment]
Also, thanks for the contribution!

**Pull request merged**
