### PR TITLE
Added Aws::CloudFormation::Stack#exists?

### PR DESCRIPTION
**Pull request by stopdropandrew**

### CODE REVIEW

**Comment by awood45** [comment]
The conflict is probably just the changelog from the last release. You can rebase or just pull the changelog out (and we can add the item on merging).

**Comment by stopdropandrew** [comment]
@awood45 - rebased

**Comment by stopdropandrew** [comment]
Test failure seems unrelated, it's happening in another pull as well

**Comment by awood45** [comment]
Pulling this down, the waiter doesn't work as intended (it will bail on the first 400 response).

I'm debugging this now.

**Comment by awood45** [comment]
Nevermind, it's working, I made a brain fart while testing. Pulling this in manually due to the merge conflict on CHANGELOG - thanks!

**Pull request merged**
