### PR TITLE
Cleanup warnings

### PR DESCRIPTION
**Pull request by mkrisher**
This PR removes an unused variable and an unused method (that assigned two unused variables). I'm using the gem in a project that has warnings turned on and Ruby 2.0 was complaining:

/var/lib/gems/2.0.0/gems/aws-sdk-resources-2.2.9/lib/aws-sdk-resources/services/s3/bucket.rb:44: warning: assigned but unused variable - error

/var/lib/gems/2.0.0/gems/aws-sdk-core-2.2.9/lib/aws-sdk-core/rest/request/endpoint.rb:105: warning: assigned but unused variable - param_name
/var/lib/gems/2.0.0/gems/aws-sdk-core-2.2.9/lib/aws-sdk-core/rest/request/endpoint.rb:106: warning: assigned but unused variable - param_value

I have a few more warnings to work through, but going to do in a followup PR in order to keep these small and clean.

### CODE REVIEW

**Comment by awood45** [comment]
Looks good on a first pass, I want to take a deeper look into `querystring_param` before merging.

**Comment by mkrisher** [comment]
Sounds good. fwiw, a quick ack on the repo didn't return any matches for 'querystring_param' other than the method when it existed.

**Comment by trevorrowe** [comment]
+1, these changes look fine to merge.

**Comment by awood45** [comment]
Thanks! Happy to look at more of these too, if you find more warnings.

**Comment by mkrisher** [comment]
No problem, I am seeing and plan on tracking down the following as well:

```
/var/lib/gems/2.0.0/gems/aws-sdk-resources-2.2.9/lib/aws-sdk-resources/services/s3/object.rb:44: warning: method redefined; discarding old copy_from
/var/lib/gems/2.0.0/gems/aws-sdk-resources-2.2.9/lib/aws-sdk-resources/operation_methods.rb:18: warning: previous definition of copy_from was here
/var/lib/gems/2.0.0/gems/aws-sdk-resources-2.2.9/lib/aws-sdk-resources/services/s3/object_summary.rb:11: warning: method redefined; discarding old copy_from
/var/lib/gems/2.0.0/gems/aws-sdk-resources-2.2.9/lib/aws-sdk-resources/operation_methods.rb:18: warning: previous definition of copy_from was here
```

**Pull request merged**
