### PR TITLE
UrlSigner methods move to module Signer, create CookieSigner

### PR DESCRIPTION
**Pull request by hamadata**
As the PHP library has, CookieSigner#signed_cookie is added.
- PHP Library
  https://github.com/aws/aws-sdk-php/blob/master/src/CloudFront/CookieSigner.php
- the related section of document
  https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-setting-signed-cookie-canned-policy.html
  https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-setting-signed-cookie-custom-policy.html

### CODE REVIEW

**Comment by hamadata** [comment]
#1255 is the correspondent issue.

**Comment by cjyclaire** [comment]
Apology for the late reply on this, cloud front url signer has been added support :) 
Could you resolve the conflicts first then we can take a look at your PR?

**Comment by hamadata** [comment]
[memo]
This conflict is caused by this commit

https://github.com/aws/aws-sdk-ruby/commit/d3981c8997baa66897ee5c3c02b86ab6b1edc0e1

In this PR, most of the lines are moved to singer.rb, which includes the change shown in the link above.
```
JSON.dump(json_hash)
```

**Comment by cjyclaire** [comment]
Wow, the history log is blowing out interestingly, could you clean those up a bit?
Or perhaps, would it be easier for you to open a new PR what includes Cookie Signer only aganist master? : ) Just @ me once it's done, I'll do the review for it. Appreciate that!

**Comment by hamadata** [comment]
Sorry, I will create a new pull-request.

**Comment by cjyclaire** [comment]
No worries, thank you : ). Closing this for now, waiting for your new PR to be reviewed : )

**Pull request closed without merging**
