### PR TITLE
Drop Ruby 2.3 and 2.4

### PR DESCRIPTION
**Pull request by mullermp**
Drops Ruby 2.3 and 2.4 for all gems

### CODE REVIEW

**Comment by jterapin** [comment]
LGTM - some docs stuff.

* Documentation [here](https://github.com/aws/aws-sdk-ruby/blob/74d24d2815cc9ff96f6c99b28552e69a05d778f6/gems/aws-sdk-core/lib/aws-sdk-sts/presigner.rb#L38) is referencing Ruby 2.3 docs.
* Seahorse H2 plugin are showing reference to Ruby 2.3:
  * [Setting to `true` to enable ALPN in HTTP2 over TLS, requires Ruby version >= 2.3 and](https://github.com/aws/aws-sdk-ruby/blob/046965e6dc7f563f046aef24d1943450e3b8bdaf/gems/aws-sdk-core/lib/seahorse/client/plugins/h2.rb#L57)

**Review by jterapin — APPROVED** [review]
LGTM

**Comment by mbaumbach** [comment]
There's a chance this change broke the AWS OpsWorks agent. Ever since 1.3.0 was released of the aws-eventstream gem with these changes, our agent no longer bundle installs correctly with this error:

```
[2023-11-22T23:47:44+00:00] ERROR: Running exception handlers
[2023-11-22T23:47:44+00:00] ERROR: Exception handlers complete
[2023-11-22T23:47:44+00:00] FATAL: Stacktrace dumped to /var/chef/runs/7d15285e-49ec-45ab-bb36-88a58ed5ffb8/local-mode-cache/cache/chef-stacktrace.out
[2023-11-22T23:47:44+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2023-11-22T23:47:44+00:00] ERROR: Expected process to exit with [0], but received '5'
---- Begin output of bundle install ----
STDOUT: Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies......
Installing aws-eventstream 1.3.0
 
Gem::InstallError: aws-eventstream requires Ruby version >= 2.5.
Using jmespath 1.6.2
Using bundler 1.12.5
An error occurred while installing aws-eventstream (1.3.0), and Bundler cannot
continue.
Make sure that `gem install aws-eventstream -v '1.3.0'` succeeds before
bundling.
STDERR: 
---- End output of bundle install ----
Ran bundle install returned 5
[2023-11-22T23:47:44+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Ideally, the OpsWorks agent would lock its aws-eventstream dependency to a version it can support, but if not this may mean all OpsWorks stacks are broken. I don't know for sure, but both of ours broke after this went live.

EDIT: We worked around this by modifying our `aws` cookbook after packaging up our custom cookbook. In the `metadata.json` file in the `aws` cookbook, we changed the gems line:

```json
"gems": [
	["aws-sdk", "~> 2"]
]
```

To:

```json
"gems": [
	["aws-eventstream", "1.2.0"],
	["aws-sigv4", "1.6.1"],
	["aws-sdk", "~> 2"]
]
```

**Comment by mullermp** [comment]
I'm so sorry this happened to you. What version of Ruby are you running and what version of Ruby is OpsWorks doing? I will make sure to propagate this to the OpsWorks team.

**Comment by mbaumbach** [comment]
@mullermp No worries, OpsWorks is running a really old version of Chef (12) and Ruby (2.3.1). I don't think there's a way to run OpsWorks with a newer version of Ruby. I figured I'd mention it in case any teams in AWS hit this in support cases and I added our workaround in case others are stuck too.

**Comment by mullermp** [comment]
Thank you, and I'm sorry that OpsWorks is running terribly old software. As a customer, other than a work around, are there upgrade paths to other services that keep more up to date software?

**Comment by mbaumbach** [comment]
Amazon has many other services that they recommend migrating off of OpsWorks, as it's now deprecated for sunset in May 2024. We're in the process right now too, but not quite there yet. :)

**Comment by nap** [comment]
@mullermp JFYI the PR say `Drop Ruby 2.4 and 2.5`.

I can see in the code: `spec.required_ruby_version = '>= 2.5'`.
I'm assuming that the intent was to drop `2.3` and `2.4`, not `2.5`, which would be aligned with what the `CHANGELOG.md` say?

**Comment by mullermp** [comment]
Oh my. Yes.. and even in the blog post, this error was not caught. I'm so sorry. I will fix this.

**Comment by gabsfm** [comment]
Thank you @mbaumbach for the suggested fix, it worked for us also.

It's fair to say this will likely affect a few OpsWorks users that (like us) are still in the process of migrating away.

Just hope they all find this discussion sooner than later! 🙈

**Comment by Daniel-ZA** [comment]
Hi team,

Does anyone know how to do the workaround when using Berkshelf as the dependency manager?

**Comment by mullermp** [comment]
I have never used Berkshelf, but based on this docs page, it seems you can add version constraints. You'll want to add the same versions as above.

https://docs.chef.io/workstation/berkshelf/

**Comment by mbaumbach** [comment]
@Daniel-ZA @mullermp I wasn't able to get the Berkshelf constraints to control the dependencies in the `aws` cookbook correctly, but admittedly I'm a novice with Berkshelf.

The way I did it, which is a pretty big hack, was to package it up normally using `berks package` and then I extracted the archive it created and went and modified the `metadata.json` inside of the `aws` cookbook and then re-archived it.

It's very manual, but since we plan to move off OpsWorks fairly soon I'm ok with it since we don't modify our custom cookbook all that often.

**Comment by gabsfm** [comment]
@Daniel-ZA we applied @mbaumbach's suggestion to our `metadata.rb` as per https://docs.chef.io/config_rb_metadata/ to get it to work with Berkshelf.

```
gem 'aws-eventstream', '1.2.0'
gem 'aws-sigv4', '1.6.1'
gem 'aws-sdk', '~> 2'
```

**Pull request merged**
